version: "3.8"

services:
  caddy:
    image: caddy
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
    - /mnt/volume/caddy:/data

  bitwarden:
    image: bitwardenrs/server
    restart: always
    env_file:
      - ../secrets/bitwarden.ignored
    volumes:
    - /mnt/volume/bitwarden:/data