version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ../secrets/postgres.ignored
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/postgres
