version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ../secrets/postgres.ignored
    ports:
    - 5432:5432
    volumes:
    - /mnt/volume/postgres:/var/lib/postgresql/data
