# https://taskfile.dev

version: '3'

tasks:

  deploy:
    cmds:
      - task: deploy:entry_point
      - task: deploy:kubernetes

  deploy:entry_point:
    dir: ansible/entry-point
    cmds:
      - ansible-playbook -v playbook.yaml -K

  deploy:kubernetes:
    dir: kubernetes
    cmds:
      - task deploy
