# https://taskfile.dev

version: '3'

silent: true

tasks:
  deploy:
    desc: Deploy all kubernetes-applications via helm (& entrypoint for minikube)
    cmds:
      - task: deploy:entry_point
      - task: deploy:helm


  deploy:entry_point:
    desc: Deploy entrypoint for minikube
    dir: ansible/entry-point
    cmds:
      - ansible-playbook -v playbook.yaml -K

  deploy:helm:
    desc: Deploy all kubernetes-applications with helm
    dir: helm
    cmds:
      - task: deploy:kubernetes
