# https://taskfile.dev

version: '3'

silent: true

tasks:

  docker-compose:postgres:
    cmds:
      - docker-compose -p postgres -f docker-compose-files/postgres-compose.yml up -d

  create-secret-files:
    cmds:
      - echo 'POSTGRES_USER=\nPOSTGRES_PASSWORD=' > secrets/postgres.ignored
