# https://taskfile.dev

version: '3'

silent: true

tasks:

  docker-compose:postgres:
    cmds:
      - docker-compose up -f docker-compose-files/postgres-compose.yml

  create-secrets:
    cmds:
      - well...
