# https://taskfile.dev

version: '3'

silent: true

tasks:
  deploy:
    desc: Deploy all kubernetes-applications via helm (& entrypoint for minikube)
    cmds:
      - task: entry_point:deploy
      - task: kubernetes:deploy
      - task: helm:deploy


  entry_point:deploy:
    desc: Deploy entrypoint for minikube
    dir: ansible/entry-point
    cmds:
      - ansible-playbook -v playbook.yaml -K

  kubernetes:deploy:
    desc: Configure kubernetes on a global level
    dir: kubernetes
    cmds:
      - task deploy

  helm:deploy:
    desc: Deploy all kubernetes-applications with helm
    dir: helm
    cmds:
      - task deploy
  helm:uninstall:
    desc: Uninstall all kubernetes-applications previously installed with helm
    dir: helm
    cmds:
      - task uninstall
