# https://taskfile.dev

version: '3'

silent: true

tasks:

  postgres:up:
    cmds:
      - docker-compose -p postgres -f docker-compose-files/postgres-compose.yml up -d
  
  postgres:down:
    cmds:
      - docker-compose -p postgres -f docker-compose-files/postgres-compose.yml down

  mariadb:up:
    cmds:
      - docker-compose -p mariadb -f docker-compose-files/mariadb-compose.yml up -d

  mariadb:down:
    cmds:
      - docker-compose -p mariadb -f docker-compose-files/mariadb-compose.yml down

  http:up:
    cmds:
      - docker-compose -p http -f docker-compose-files/http-compose.yml up -d

  http:down:
    cmds:
      - docker-compose -p http -f docker-compose-files/http-compose.yml down

  create-secret-files:
    cmds:
      - |
        file=secrets/postgres.ignored
        if [ ! -f "$file" ]; then
          echo "POSTGRES_USER=root" > "$file"
          echo "POSTGRES_PASSWORD=$(openssl rand -base64 32)" >> "$file"
        fi
      - |
        file=secrets/mariadb.ignored
        if [ ! -f "$file" ]; then
          echo "MYSQL_ROOT_PASSWORD=$(openssl rand -base64 32)" > "$file"
        fi
      - |
        file=secrets/bitwarden.ignored
        if [ ! -f "$file" ]; then
          echo "ADMIN_TOKEN=$(openssl rand -base64 32)" > "$file"
        fi
