# https://taskfile.dev

version: '3'

silent: true

tasks:

  postgres:up:
    cmds:
      - docker-compose -p postgres -f docker-compose-files/postgres-compose.yml up -d
  
  postgres:down:
    cmds:
      - docker-compose -p postgres -f docker-compose-files/postgres-compose.yml down

  mariadb:up:
    cmds:
      - docker-compose -p mariadb -f docker-compose-files/mariadb-compose.yml up -d

  mariadb:down:
    cmds:
      - docker-compose -p mariadb -f docker-compose-files/mariadb-compose.yml down

  create-secret-files:
    cmds:
      - |
        file=secrets/postgres.ignored
        if [ ! -f "$file" ]; then
          echo 'POSTGRES_USER=\nPOSTGRES_PASSWORD=' > "$file"
        fi
      - |
        file=secrets/mariadb.ignored
        if [ ! -f "$file" ]; then
          echo 'MYSQL_ROOT_PASSWORD=' > "$file"
        fi
