apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }} # within cluster
      targetPort: {{ .port }} # container port
      protocol: {{ .protocol }}
    {{- end}}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
