- hosts: localhost
  connection: local
  run_once: true

  tasks:
    - name: Get minikube ip
      command: "minikube ip"
      register: r_minikube_ip
    - set_fact:
        minikube_ip: "{{ r_minikube_ip.stdout }}"
    - name: Forward port {{ item.port }} to minikube
      shell:
        project_name: forward-port-{{ item.port }}
        definition:
          port-forwarder:
            image: tillhoff/socat
            extra_hosts:
              - "minikube:{{ minikube_ip }}"
            ports: "{{ item.port }}:{{ item.port }}"
            command: socat TCP-LISTEN:{{ item.port }},fork TCP:{{ minikube_ip }}:{{ item.port }}
      loop:
        - 80
