- hosts: localhost
  connection: local
  run_once: true
  gather_facts: no

  tasks:
    - name: Install python3 and python-pip3
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
    - name: Install required python packages
      pip:
        executable: pip3
        name: "{{ item }}"
      loop:
      - docker
      - docker-compose
    - name: Get minikube ip
      command: "minikube ip"
      register: r_minikube_ip
      changed_when: false
    - set_fact:
        minikube_ip: "{{ r_minikube_ip.stdout }}"
    - name: "Stop all port-forwarding container"
      shell:  docker container stop $(docker container ls -q --filter name=forward-port-*)
      ignore_errors: yes
    - name: "Forward port to minikube"
      docker_compose:
        state: present
        project_name: "forward-port-{{ port.from }}-to-minikube"
        definition:
          socat:
            image: tillhoff/socat
            extra_hosts:
              - "minikube:{{ minikube_ip }}"
            container_name: "forward-port-{{ port.from }}-to-minikube"
            ports: 
              - "{{ port.from }}:{{ port.to }}"
            command: |
              socat TCP-LISTEN:{{ port.from }},fork TCP:{{ minikube_ip }}:{{ port.to }};
      vars:
        port:
          from: 80
          to: 80
    - name: "Forward port to minikube"
      docker_compose:
        state: present
        project_name: "forward-port-{{ port.from }}-to-minikube"
        definition:
          socat:
            image: tillhoff/socat
            extra_hosts:
              - "minikube:{{ minikube_ip }}"
            container_name: "forward-port-{{ port.from }}-to-minikube"
            ports: 
              - "{{ port.from }}:{{ port.to }}"
            command: |
              socat TCP-LISTEN:{{ port.from }},fork TCP:{{ minikube_ip }}:{{ port.to }};
      vars:
        port:
          from: 443
          to: 443
    - name: "Forward port to minikube"
      docker_compose:
        state: present
        project_name: "forward-port-{{ port.from }}-to-minikube"
        definition:
          socat:
            image: tillhoff/socat
            extra_hosts:
              - "minikube:{{ minikube_ip }}"
            container_name: "forward-port-{{ port.from }}-to-minikube"
            ports: 
              - "{{ port.from }}:{{ port.to }}"
            command: |
              socat TCP-LISTEN:{{ port.from }},fork TCP:{{ minikube_ip }}:{{ port.to }};
      vars:
        port:
          from: 9999
          to: 9999