- hosts: localhost
  connection: local
  run_once: true

  tasks:
  - name: Install automatic iptables restore
    become: true
    apt:
      name: iptables-persistent
      state: present
  - name: Enable port forwarding in sysctl
    become: true
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      sysctl_set: yes # verify
      reload: true
      state: present
  - name: Setup postrouting masquerade
    become: true
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: "{{ ansible_default_ipv4.interface }}"
      jump: MASQUERADE
      comment: Enable masquerading, setup with ansible

  - name: Setup prerouting port forwarding
    become: true
    iptables:
      table: nat
      chain: PREROUTING
      in_interface: eth0
      ip_version: "{{ item.ip_version }}"
      protocol: "{{ item.protocol }}"
      destination: "{{ item.to_ip }}"
      destination_port: "{{ item.from_port }}"
      jump: REDIRECT
      to_ports: "{{ item.to_port }}"
      state: "{{ item.state }}"
      comment: Port forwarding, setup with ansible
    notify:
    - Save iptable rules
    loop:
    - ip_version: ipv4
      protocol: tcp
      from_port: 8080
      to_ip: 127.0.0.1
      to_port: 80
      state: present
    - ip_version: ipv4
      protocol: tcp
      from_port: 8443
      to_ip: 127.0.0.1
      to_port: 443
      state: present

  handlers:
  - name: Save iptable rules
    become: true
    shell: iptables-save > /etc/iptables/rules.v4 && ip6tables-save > /etc/iptables/rules.v6
