replicaCount: 1

image:
  repository: caddy
  pullPolicy: IfNotPresent

ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  - name: healthcheck
    port: 9999
    protocol: TCP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

volume:
  capacity: 1Gi

caddyfile: |
  {
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
  }

  alpha.enforge.de {
    respond "You are now securely on the caddy within kubernetes! Well done!"
  }
  alpha-centauri.enforge.de {
    respond "You are now securely on the caddy within kubernetes! Good job!"
  }
  pw.enforge.de {
    reverse_proxy http://bitwarden-service.default.svc.cluster.local
  }
  push.enforge.de {
    reverse_proxy http://gotify-service.default.svc.cluster.local
  }
  :9999 {
    respond "I'm healthy!"
    #redir alpha-centauri.enforge.de{uri}
    #reverse_proxy caddy-service.default.svc.cluster.local
  }
