apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
      - name: bitwarden
        image: bitwardenrs/server:1.16.3
        ports:
        - containerPort: 80
        volumeMounts:
        - name: bitwarden-data
          mountPath: /data
          readOnly: false
      volumes:
      - name: bitwarden-data
        persistentVolumeClaim:
          claimName: bitwarden-pvc
