apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  selector:
    app: caddy
  type: NodePort
  ports:
    - name: HTTP
      protocol: TCP
      port: 80 # within cluster
      targetPort: 80 # container port
      nodePort: 80 # external
    - name: HTTPS
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 443
    - name: HEALTHCHECK
      protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 9999
