apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configuration
  labels:
    app: caddy
data:
  Caddyfile: |
    alpha.enforge.de {
    	respond "You are now securely on the caddy within kubernetes! Well done!"
    }
    alpha-centauri.enforge.de {
      respond "You are now securely on the caddy within kubernetes! Good job!"
    }
    pw.enforge.de:80 {
      reverse_proxy bitwarden-service.default.svc.cluster.local
    }
    :9999 {
      respond "I'm healthy!"
      #redir alpha-centauri.enforge.de{uri}
      #reverse_proxy caddy-service.default.svc.cluster.local
    }
