apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configuration
  labels:
    app: caddy
data:
  Caddyfile: |
    #alpha.enforge.de {
    #	respond "You are now securely on the caddy within kubernetes! Good job!"
    #}
    :9999 {
      respond "I'm healthy!"
      #reverse_proxy caddy-service.web.svc.cluster.local:80
    }
