apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configuration
  labels:
    app: caddy
data:
  Caddyfile: |
    alpha.enforge.de:80 {
    	respond "You are now on the caddy within kubernetes! Good job!"
    }
    #:443 {
    #  respond "Hi!"
    #}
    :9999 {
      reverse_proxy caddy-service.web.svc.cluster.local:80
    }
    #alpha.enforge.de:9999 {
    #  respond "I'm healthy!"
    #}
