apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:2.1.1
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 9999
        volumeMounts:
        - name: caddy-configuration
          mountPath: /etc/caddy/Caddyfile
          readOnly: true
          subPath: Caddyfile
        - name: caddy-data
          mountPath: /data
          readOnly: false
      volumes:
      - name: caddy-configuration
        configMap:
          name: caddy-configuration
          items:
          - key: Caddyfile
            path: Caddyfile
            mode: 0644
      - name: caddy-data
        persistentVolumeClaim:
          claimName: caddy-pvc
