apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configuration
  labels:
    app: caddy
data:
  Caddyfile: |
    #alpha.enforge.de {
    #	redir alpha-centauri.enforge.de{uri}
    #}
    #alpha-centauri.enforge.de {
    #  respond "You are now securely on the caddy within kubernetes! Good job!"
    #}
    :9999 {
      path /healthcheck
      respond "I'm healthy!"
      #reverse_proxy alpha-centauri.enforge.de
    }
