apiVersion: v1
kind: Service
metadata:
  name: gotify-service
  labels:
    app: gotify
spec:
  selector:
    app: gotify
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80 # within cluster
      targetPort: 80 # container port
