# https://taskfile.dev

version: '3'

tasks:

  deploy:
    cmds:
      - task: deploy:caddy

  deploy:caddy:
    cmds:
      - task: deploy:caddy:deployment
      - task: deploy:caddy:service
      - task: deploy:caddy:configmap
  deploy:caddy:deployment:
    cmds:
      - cmd: kubectl create namespace web
        ignore_error: true
      - kubectl apply -f ./caddy_deployment.yaml --namespace web
  deploy:caddy:service:
    cmds:
      - cmd: kubectl create namespace web
        ignore_error: true
      - kubectl apply -f ./caddy_service.yaml --namespace web
  deploy:caddy:configmap:
    cmds:
      - cmd: kubectl create namespace web
        ignore_error: true
      - kubectl apply -f ./caddy_configmap.yaml --namespace web