# https://taskfile.dev

version: '3'

tasks:

  deploy:
    desc: Deploy everything
    cmds:
      - task: deploy:persistentvolume


  deploy:persistentvolume:
    desc: Deploy persistentvolume
    cmds:
      - kubectl apply -f minikube_persistentvolume.yaml
