# https://taskfile.dev

version: '3'

silent: true

tasks:
  deploy:
    desc: Deploy all kubernetes-applications with helm
    cmds:
      - task: deploy:bitwarden
      - task: deploy:caddy
      - task: deploy:gotify


  deploy:bitwarden:
    desc: Deploy bitwarden with helm
    dir: bitwarden
    cmds:
      - task deploy

  deploy:caddy:
    desc: Deploy caddy with helm
    dir: caddy
    cmds:
      - task deploy

  deploy:gotify:
    desc: Deploy gotify with helm
    dir: gotify
    cmds:
      - task deploy

  uninstall:
    desc: Uninstall all applications
    cmds:
      - helm uninstall bitwarden
      #- helm uninstall caddy # removed, as it will always renew certs, which leads to reaching acme rate limits
      - helm uninstall gotify
