# https://taskfile.dev

version: '3'

tasks:

  deploy:
    desc: Deploy all charts
    cmds:
      - task: deploy:traefik

  deploy:traefik:
    desc: Deploy traefik
    cmds:
      - helm install --name traefik --values traefik-values.yaml stable/traefik
