apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  selector:
    app: caddy
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # within cluster
      targetPort: 80 # container port
      nodePort: 80 # external
