apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-deployment
  labels:
    app: caddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:2.1.1
        ports:
        - containerPort: 80
        - containerPort: 443
        volumes:
        - name: caddy-configuration
          configMap:
            name: caddy-configuration
            items:
            - key: Caddyfile
              path: Caddyfile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configuration
data:
  Caddyfile: |
    :80 {
    	respond "You are now on the caddy within kubernetes! Good job!"
    }
