# https://taskfile.dev

version: '3'

tasks:
  deploy:deployment:
    cmds:
      - kubectl apply -f ./deployment_caddy.yaml

  deploy:service:
    cmds:
      - kubectl apply -f ./service_caddy.yaml
  
  deploy:reverseproxy:
    cmds:
      - docker-compose up
