# https://taskfile.dev

version: '3'

tasks:

  deploy:
    cmds:
      - task: deploy:caddy

  deploy:caddy:
    cmds:
      - task: deploy:caddy:deployment
      - task: deploy:caddy:service
      - task: deploy:caddy:configmap
  deploy:caddy:deployment:
    cmds:
      - kubectl apply -f ./caddy_deployment.yaml
  deploy:caddy:service:
    cmds:
      - kubectl apply -f ./caddy_service.yaml
  deploy:caddy:configmap:
    cmds:
      - kubectl apply -f ./caddy_configmap.yaml